Week-1 - My solution for Boolean Operators, Fermat Numbers and Look-and-say Sequence
vadimkatsel/Scala_Homeworks pull request #1
Opened 2022-11-02 12:17 UTC by vadimkatsel

Thanks for the rather quick response to the invitation!!!

2022-11-04 10:41 UTC, IgorWolkov commented on scala-course-2022-autumn/src/main/scala/karazin/scala/users/group/week1/homework/Homework.scala
> +    def not(b: Boolean): Boolean =
Get rid of `return`. Everywhere.

2022-11-04 10:42 UTC, IgorWolkov commented on scala-course-2022-autumn/src/main/scala/karazin/scala/users/group/week1/homework/Homework.scala
> +      if (b) return false
I'd prefer `if b then false ... `.

2022-11-04 10:42 UTC, IgorWolkov commented on scala-course-2022-autumn/src/main/scala/karazin/scala/users/group/week1/homework/Homework.scala
> +    def and(left: Boolean, right: Boolean): Boolean =
This and isn't eager enough, because right is evaluated even if it is not used.

2022-11-04 10:42 UTC, IgorWolkov commented on scala-course-2022-autumn/src/main/scala/karazin/scala/users/group/week1/homework/Homework.scala
> +    def or(left: Boolean, right: Boolean): Boolean =
This or isn't eager enough, because right is evaluated even if it is not used.

2022-11-04 10:43 UTC, IgorWolkov commented on scala-course-2022-autumn/src/main/scala/karazin/scala/users/group/week1/homework/Homework.scala
> +      if(left)
Suppose `left` is true. What value fully determine the value of `and`?

2022-11-04 10:44 UTC, IgorWolkov commented on scala-course-2022-autumn/src/main/scala/karazin/scala/users/group/week1/homework/Homework.scala
> +      else multiplication(a,b-1) + a
Make it tail-recursive.

2022-11-04 10:45 UTC, IgorWolkov commented on scala-course-2022-autumn/src/main/scala/karazin/scala/users/group/week1/homework/Homework.scala
> +      else multiplication(a,b-1) + a
Add spaces everywhere: `b-1` => `b - 1`.

2022-11-04 10:46 UTC, IgorWolkov requested changes
No tests no approves.
Please review the comments.

2022-11-07 18:25 UTC, IgorWolkov commented on scala-course-2022-autumn/src/main/scala/karazin/scala/users/group/week1/homework/Homework.scala
> +  def and(left: Boolean,right : Boolean): Boolean = if not(left) then false else right
Excellent.

2022-11-07 18:26 UTC, IgorWolkov requested changes
Test are required.

2022-11-08 17:29 UTC, vadimkatsel commented
I don't really sure that I fully understand what test is it. One more guide on tests is required.

2022-11-11 11:23 UTC, IgorWolkov commented on scala-course-2022-autumn/src/main/scala/karazin/scala/users/group/week1/homework/Homework.scala
> +  def and(left: Boolean,right : Boolean): Boolean = if not(left) then false else right
This `and` isn't eager enough, because right is evaluated even if it is not used.

2022-11-11 11:24 UTC, IgorWolkov commented on scala-course-2022-autumn/src/main/scala/karazin/scala/users/group/week1/homework/Homework.scala
> +  def or(left: Boolean, right: Boolean): Boolean = if left then true else right
This `or` isn't eager enough, because `right` is evaluated even if it is not used.

2022-11-15 08:32 UTC, IgorWolkov commented on scala-course-2022-autumn/src/test/scala/karazin/scala/users/group/week1/homework/HomeworkSpecification.scala
>    property("and") = forAll { (pair: (Boolean, Boolean)) =>
Please add a new tests to prove that `and` is eager.
Hint:
1. use `propBoolean` instead of `forAll` because all necessary values are known.
2. to prove that `right` part is not invoked, throw an error in the place of a second argument.

2022-11-15 08:32 UTC, IgorWolkov commented on scala-course-2022-autumn/src/test/scala/karazin/scala/users/group/week1/homework/HomeworkSpecification.scala
>    property("or") = forAll { (pair: (Boolean, Boolean)) =>
Please add a new test to prove that `or` is eager.
Hint:
1. use `propBoolean` instead of `forAll` because all necessary values are known.
2. to prove that `right` part is not invoked, throw an error in the place of a second argument.

2022-11-15 08:33 UTC, IgorWolkov requested changes
Almost done, please add two tests.

2022-11-23 11:28 UTC, IgorWolkov commented on scala-course-2022-autumn/src/main/scala/karazin/scala/users/group/week1/homework/Homework.scala
> +  def lookAndSaySequence(number: String): String = {
Looks like tablulation in the body of this method is a bit corrupted. Please add extra spaces.

2022-11-23 11:32 UTC, IgorWolkov commented on scala-course-2022-autumn/src/test/scala/karazin/scala/users/group/week1/homework/HomeworkSpecification.scala
>    property("and") = forAll { (pair: (Boolean, Boolean)) =>
Usually it's a bad idea to overweight a test with extra case.
I ask you add a **new** tests, not a new cases to the **existing** one.
The test could looks like:
```
property("some smart name") = propBoolean {
  val error = ??? // some exception with meaningful text message (any way it should not be thrown).
  and(false, error) == ???
}
```

Please do the same for `or` case.

2022-11-23 11:33 UTC, IgorWolkov requested changes
Some improvements are required.

2022-11-25 10:17 UTC, IgorWolkov commented on scala-course-2022-autumn/src/test/scala/karazin/scala/users/group/week1/homework/HomeworkSpecification.scala
> +    (and(left, right) == (left && right)) && (and(false,(7/0 == 2)) == false)
Please get rid of `(and(false,(7/0 == 2)) == false)`, I've done the test for this case.

2022-11-25 10:17 UTC, IgorWolkov commented on scala-course-2022-autumn/src/test/scala/karazin/scala/users/group/week1/homework/HomeworkSpecification.scala
> +    (or(left, right) == (left || right)) && (or(true,(7/0 == 2)) == true)
Please get rid of `(or(true,(7/0 == 2)) == true)`, I've done the test for this case.

2022-11-25 10:17 UTC, IgorWolkov requested changes
Final improvement and that's all.

2022-11-25 12:58 UTC, vadimkatsel commented
Final improvement.

2022-11-27 11:07 UTC, merged

2022-12-08 11:36 UTC, IgorWolkov commented
Looks like I haven't approved merging this code to master. Why it was merged?