Week 2 - Class Rational
vadimkatsel/Scala_Homeworks pull request #2
Opened 2022-11-23 21:13 UTC by vadimkatsel

2022-12-01 10:48 UTC, IgorWolkov commented on scala-course-2022-autumn/src/main/scala/karazin/scala/users/group/week2/homework/Homework.scala
> +    override def equals(other: Any): Boolean =
Please review https://www.baeldung.com/java-equals-hashcode-contracts

2022-12-01 10:52 UTC, IgorWolkov requested changes
Almost done, please fix the issue with hashcode.

2022-12-04 11:47 UTC, IgorWolkov approved these changes
Well done!

2022-12-04 11:51 UTC, vadimkatsel commented
Can this HW be merged?

2022-12-07 00:02 UTC, merged